### ISSUE TITLE
Function components cannot be given refs

### ISSUE THREAD

**Issue by justasno** [devias-io/react-material-dashboard#14] opened 2019-06-20 11:55 UTC
Fresh install, whenever sidebar is opened I get this error, what is it about:

> Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
> 
> Check the render method of `ForwardRef(ListItem)`.
>     in NavLink (created by ForwardRef(ListItem))
>     in ForwardRef(ListItem) (created by WithStyles(ForwardRef(ListItem)))
>     in WithStyles(ForwardRef(ListItem)) (at Sidebar/index.jsx:86)
>     in div (created by ForwardRef(List))
>     in ForwardRef(List) (created by WithStyles(ForwardRef(List)))
>     in WithStyles(ForwardRef(List)) (at Sidebar/index.jsx:82)
>     in nav (at Sidebar/index.jsx:46)
>     in Sidebar (created by WithStyles(Sidebar))
>     in WithStyles(Sidebar) (at Dashboard/index.jsx:66)
>     in div (created by ForwardRef(Paper))
>     in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
>     in WithStyles(ForwardRef(Paper)) (created by Transition)
>     in Transition (created by ForwardRef(Slide))
>     in ForwardRef(Slide) (created by WithTheme(ForwardRef(Slide)))
>     in WithTheme(ForwardRef(Slide)) (created by TrapFocus)
>     in TrapFocus (created by Modal)
>     in div (created by Modal)
>     in ForwardRef(Portal) (created by Modal)
>     in Modal (created by ForwardRef(Modal))
>     in ForwardRef(Modal) (created by WithTheme(ForwardRef(Modal)))
>     in WithTheme(ForwardRef(Modal)) (created by ForwardRef(Drawer))
>     in ForwardRef(Drawer) (created by WithStyles(ForwardRef(Drawer)))
>     in WithStyles(ForwardRef(Drawer)) (at Dashboard/index.jsx:59)
>     in Dashboard (created by WithWidth(Dashboard))
>     in WithWidth(Dashboard) (created by WithStyles(WithWidth(Dashboard)))
>     in WithStyles(WithWidth(Dashboard)) (at Dashboard/index.jsx:42)
>     in Dashboard (created by WithStyles(Dashboard))
>     in WithStyles(Dashboard) (created by Context.Consumer)
>     in Route (at Routes.jsx:26)
>     in Switch (at Routes.jsx:20)
>     in Routes (at App.jsx:37)
>     in Router (at App.jsx:36)
>     in ThemeProvider (at App.jsx:35)
>     in App (at src/index.js:10)

**Comment by devias-io** [comment] 2019-06-21 07:01
@justasno Hi there! Thanks for trying our product.

It's a known issue and we fixed it in the PRO version that will be released soon. We will updated this FREE repo entirely right after the release.

The problem is generated by the `LinkItem` component, that uses `NavLink` as a component prop. It's related with the "ref" forwarding. To fix this you can do the following:

Instead of using directly the NavLink as a prop, you can wrap this component into a functional component that uses React.forwardRef.

Example:
```
const CustomNavLink = React.forwardRef((props, ref) => (
  <div ref={ref}>
    <NavLink {...props} />
  </div>
));
```

And then in your ListItem component you add the `CustomNavLink` instead of `NavLink`.

```
<ListItem
  activeClassName={classes.activeListItem}
  className={classes.listItem}
  component={CustomNavLink}
  // rest
```

We did not test it in the FREE version, but it should work. We will try to update the repo as soon as possible.

Please let us know if it did the job.


Thank you,
Devias Team

**Comment by VeirryAu** [comment] 2019-06-22 16:48
Thanks, it solve my problem.

**Closed** 2019-06-23 06:29 UTC

**Comment by zmeyc** [comment] 2019-07-29 06:41
@devias-io I think it should be
```
const NavLinkWithRef = React.forwardRef((props, ref) => <NavLink innerRef={ref} {...props} />)
```
to link to inner component of NavLink. Both Link and NavLink have innerRef prop.

https://material-ui.com/components/buttons/#third-party-routing-library

**Comment by devias-io** [comment] 2019-07-29 09:33
@zmeyc You're right, we will add this in the future update.
Thanks for the info!

**Comment by ogg130** [comment] 2020-01-27 01:18
> @justasno Hi there! Thanks for trying our product.
> 
> It's a known issue and we fixed it in the PRO version that will be released soon. We will updated this FREE repo entirely right after the release.
> 
> The problem is generated by the `LinkItem` component, that uses `NavLink` as a component prop. It's related with the "ref" forwarding. To fix this you can do the following:
> 
> Instead of using directly the NavLink as a prop, you can wrap this component into a functional component that uses React.forwardRef.
> 
> Example:
> 
> ```
> const CustomNavLink = React.forwardRef((props, ref) => (
>   <div ref={ref}>
>     <NavLink {...props} />
>   </div>
> ));
> ```
> 
> And then in your ListItem component you add the `CustomNavLink` instead of `NavLink`.
> 
> ```
> <ListItem
>   activeClassName={classes.activeListItem}
>   className={classes.listItem}
>   component={CustomNavLink}
>   // rest
> ```
> 
> We did not test it in the FREE version, but it should work. We will try to update the repo as soon as possible.
> 
> Please let us know if it did the job.
> 
> Thank you,
> Devias Team

Thanks for the explanation, this worked for me! 

By the way, Material UI rocks!
